#arch: arm64-graviton2 # in AWS over Graviton2 CPU
#virt: lxd             # required, routes to an LXD container
# os: linux             required for arch different than amd64
# dist: xenial           or bionic | xenial with xenial as default
# group: edge
  
language: C
services:
- docker
cache:
  directories:
    - docker_cache

before_script:
#- docker load -i docker_images/images.tar || true
#-  TOKEN=$GITHUB_TOKEN ./geometry2_teex.sh build_docker
- |
  echo Now loading...
  filename=docker_cache/saved_images.tar
  mkdir -p docker_cache
  if [[ -f "$filename" ]] && $USE_CACHE; then
    echo "got one from cache."
    docker load < "$filename"
  else
    echo "from scratch";
    docker build --build-arg GIT_ACCESS_TOKEN=$GITHUB_TOKEN -t $IMAGE .
    if $USE_CACHE; then docker save -o "$filename" $IMAGE; fi 
  fi

#before_script:
#-    docker build --build-arg GIT_ACCESS_TOKEN=$GITHUB_TOKEN -t $IMAGE .
  




script:

- echo "19h04 29 mar"

- echo "try01"
- docker run  --privileged  "${IMAGE}" /bin/bash -c "ls -l /proc/sys/kernel/core_pattern && whoami && pwd && ls -l"
- echo "try02"
- docker run --privileged "${IMAGE}" sudo bash -c  "echo core > /proc/sys/kernel/core_pattern"
- echo "try03"
- docker run --privileged "${IMAGE}"  sudo bash -c 'sysctl -w kernel.core_pattern="core7"'
- docker run --privileged "${IMAGE}" bash -c  "ls -l /proc/sys/kernel/core_pattern; cat /proc/sys/kernel/core_pattern"


# - echo "try03"
# - docker run --privileged "${IMAGE}" sudo /bin/bash -c  "echo core > /proc/sys/kernel/core_pattern"

# - echo "try04"
# - sudo docker run --privileged  "${IMAGE}"  sudo /bin/bash -c  "echo core > /proc/sys/kernel/core_pattern"

# - echo "try05"
# - sudo docker run --privileged  "${IMAGE}"  sudo /bin/bash -c  "sudo echo core > /proc/sys/kernel/core_pattern"

#-     docker run --privileged "${IMAGE}" /bin/bash -c "echo core > /proc/sys/kernel/core_pattern"


# - echo "Triggered 10h34"
# - gcc hello.c
# - echo "BEFORE"
# - ls -l
# - ./geometry2_teex.sh shape
# - echo "AFTER"
# - ls -l
# - - ./geometry2_teex.sh fuzz
# - ls opt/ros_ws/src/geometry2/test_tf2/test/buffer_core_test.cpp/out/queue/

env:
  global:
  - IMAGE=test04 
  - USE_CACHE=true
  - MOUNT=/mnt/local
  - secure: 0c1qA4Lz5tg3bKVxsDMp3eugv1TQXhBb25X8ObwMnqTxK//u7pu9QkH0wEf5vN/B0u4uYAai/08j281Ym1VANtfg+Iw+TDIuLK7WiZtN19Rp98zkmo/n71trrl8eWHydFCWAtpOzgAgPIvs8sdR0tsUemnANjUfc/TRJHMp7ARTAvUez80CuhHdkyZXLWgY5CrLYUIuZQPoziQDkmxawLs5GRkQlAdVfbMXkzyRtpxwBcjLjlIbZRvV4rcyLntiBVNVTUXV9mO3UtnJwpxsXtKDELyPNSLfLPldk9i6GkhqXsUJzFiKjGeSGOtKvWZaz0oagOzP/f+jWOvAVrXQm9p7crR4raui9OoXWFkr+EKwG3gfaVVf07DzAoYQgjt7EnOWrAMfWIqmDCc7AGwPeykdjJiPU7hJjAsny5ELNWEUpDRR+18946Vgq/NLmnTOr5bCuZtQWR5+f4twB3ncyrkL5+i0pPwNUso+vNHHoxv+k0aLQPj65JWmkBM9PRpIjbyz5Aalfvumb69sV2rIoiDqrVu0lCgByrv69iOHo8IE4eNb2bqwh377Q62iW0cPmeS52MNVFblZQXICpoSjPy0QhZnnU8PlfOtuIUhl/97RqkXIzl1qcP+Uvajo3ZTQ/dC8yt4412BiE9PxXSib65QLRra3emdADzGrgfPYJo54=
